// vi:nu:et:sts=4 ts=4 sw=4 tw=90
/*
 * File:   j1939tbl.c
 *	Generated by Vogel 05/20/2015 11:48:08
 *
 * Created on December 30, 2014
 */

 
/*
 This is free and unencumbered software released into the public domain.
 
 Anyone is free to copy, modify, publish, use, compile, sell, or
 distribute this software, either in source code form or as a compiled
 binary, for any purpose, commercial or non-commercial, and by any
 means.
 
 In jurisdictions that recognize copyright laws, the author or authors
 of this software dedicate any and all copyright interest in the
 software to the public domain. We make this dedication for the benefit
 of the public at large and to the detriment of our heirs and
 successors. We intend this dedication to be an overt act of
 relinquishment in perpetuity of all present and future rights to this
 software under copyright law.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 
 For more information, please refer to <http://unlicense.org/>
 */




//*****************************************************************
//* * * * * * * * * * * *  Data Definitions   * * * * * * * * * * *
//*****************************************************************

/* Header File Inclusion */
#include "j1939tbl_internal.h"



#ifdef	__cplusplus
extern "C" {
#endif
    

    
#ifdef	__cplusplus
    extern	"C" {
#endif
        
        
#ifdef XYZZY
        
        const
        J1939_SPN_TYPE      SAEbs01 = {  // Bits/States
            86,             // SAE Type
            1,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            1,              // Operating Max
            0,              // Data Min
            1               // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs02 = {  // Bits/States
            87,             // SAE Type
            2,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            3,              // Operating Max
            0,              // Data Min
            3               // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs03 = {  // Bits/States
            88,             // SAE Type
            3,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            7,              // Operating Max
            0,              // Data Min
            7               // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs04 = {  // Bits/States
            89,             // SAE Type
            4,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            15,             // Operating Max
            0,              // Data Min
            15              // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs05 = {  // Bits/States
            90,             // SAE Type
            5,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            31,             // Operating Max
            0,              // Data Min
            31              // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs06 = {  // Bits/States
            91,             // SAE Type
            6,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            63,             // Operating Max
            0,              // Data Min
            63              // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs07 = {  // Bits/States
            92,             // SAE Type
            7,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            127,            // Operating Max
            0,              // Data Min
            127             // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs08 = {  // Bits/States
            93,             // SAE Type
            8,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            255,            // Operating Max
            0,              // Data Min
            255             // Data Max
        };
        
        
        const
        J1939_SPN_TYPE      SAEpc05 = {  // Percent %
            45,             // SAE Type
            8,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            -125,           // Offset
            0,              // Round
            -125,           // Operating Min
            125,            // Operating Max
            0,              // Data Min
            250             // Data Max
        };
        
        
        const
        J1939_SPN_TYPE      SAEpr07 = { // Pressure in Kpa
            53,             // SAE Type
            8,              // Length in Bits
            0,              // Decimal places
            2,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            500,            // Operating Max
            0,              // Data Min
            250             // Data Max
        };
        
        
        static
        const
        J1939_SPN_TYPE      bits64 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            64,     1,     1,      0,     0,     0,     0,      0,     0
        };
        
        
        static
        const
        J1939_SPN_TYPE      percent01 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            8,     4,    10,      0,     2,     0,   100,      0,   250
        };
        
        static
        const
        J1939_SPN_TYPE      percent03 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            8,     1,     1,      0,     0,     0,   125,      0,   250
        };
        
        
        static
        const
        J1939_SPN_TYPE      pressure01 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            8,     5,    10,      0,     2,     0,   125,      0,   250
        };
        
        
        // Source Address (SA) for a device
        static
        const
        J1939_SPN_TYPE      sourceAddress = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            8,     1,     1,      0,     0,     0,   253,      0,   255
        };
        
        
        static
        const
        J1939_SPN_TYPE      temp01 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            8,     1,     1,    -40,     2,   -40,   210,      0,   250
        };
        
        static
        const
        J1939_SPN_TYPE      temp02 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            16,  3125, 10000,   -273,  5000,  -273,  1735,      0, 55520
        };
        
        
        static
        const
        J1939_SPN_TYPE      velocityRotational01 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            16,   125,  1000,      0,   500,     0,  8031,      0, 64255
        };
#endif
        
        
        // SPN 51 - Throttle Position - The position of the valve used to regulate
        // the supply of a fluid, usually air or fuel/air mixture, to an engine.
        // 0% represents no supply and 100% is full supply.
        static
        const
        J1939_SPN           spn51 = {
            51,
            0,
            NULL    /*&percent01*/,
            "Throttle Position"
        };
        
        
        // SPN 52 - Engine Intercooler Temperature - Temperature of liquid found in the
        // intercooler located after the turbocharger.
        static
        const
        J1939_SPN           spn52 = {
            52,
            0,
            NULL    /*&temp01*/,
            "Engine Intercooler Temperature"
        };
        
        
        // SPN 69 - Two Speed Axle Switch -
        // 00 Low speed range
        // 01 High speed range
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn69 = {
            69,
            0,
            NULL    /*&???*/,
            "Two Speed Axle Switch"
        };
        
        
        // SPN 70 - Parking Brake Switch -
        // 00 Parking brake not set
        // 01 Parking brake set
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn70 = {
            70,
            0,
            NULL    /*&???*/,
            "Parking Brake Switch"
        };
        
        
        // SPN 74 - Maximum Vehicle Speed Limit -
        static
        const
        J1939_SPN           spn74 = {
            74,
            0,
            NULL    /*&???*/,
            "Maximum Vehicle Speed Limit"
        };
        
        
        // SPN 79 - Road Surface Temperature
        static
        const
        J1939_SPN           spn79 = {
            79,
            0,
            NULL    /*&???*/,
            "Road Surface Temperature"
        };
        
        
        // SPN 84 - Wheel-Based Vehicle Speed -
        static
        const
        J1939_SPN           spn84 = {
            84,
            0,
            NULL    /*&???*/,
            "Wheel-Based Vehicle Speed"
        };
        
        
        // SPN 86 - Cruise Control Set Speed -
        static
        const
        J1939_SPN           spn86 = {
            86,
            0,
            NULL    /*&???*/,
            "Cruise Control Set Speed"
        };
        
        
        static
        const
        J1939_SPN           spn87 = {
            87,
            0,
            NULL    /*&???*/,
            "Cruise Control High Set Limit Speed"
        };
        
        
        static
        const
        J1939_SPN           spn88 = {
            88,
            0,
            NULL    /*&???*/,
            "Cruise Control Low Set Limit Speed"
        };
        
        
        // SPN 91 - Accelerator Pedal Position 1 - The ratio of actual position of the
        // analog engine speed/torque request input device (such as an accelerator pedal
        // or throttle lever) to the maximum position of the input device. This parameter
        // is intended for the primary accelerator control in an application. If an appli-
        // cation has only one accelerator control, use SPN 91. For on-highway vehicles,
        // this will typically be the operator's accelerator pedal. Although it is used
        // as an input to determine powertrain demand, it also provides anticipatory
        // information to transmission and ASR algorithms about driver actions. In marine
        // applications, this will typically be the operator's throttle lever. If a low
        // idle validation switch is used in conjunction with accelerator pedal position
        // 1, use Accelerator Pedal Low Idle Switch 1, SPN 558.
        static
        const
        J1939_SPN           spn91 = {
            91,
            0,
            NULL    /*&percent01*/,
            "Accelerator Pedal Position 1"
        };
        
        
        // SPN 92 - Percent Load At Current Speed - The ratio of actual engine percent
        // torque (indicated) to maximum indicated torque available at the current en-
        // gine speed, clipped to zero torque during engine braking.
        static
        const
        J1939_SPN           spn92 = {
            92,
            0,
            NULL    /*&percent03*/,
            "Percent Load At Current Speed"
        };
        
        
        // SPN 98 - Engine Oil Level - Ratio of current volume of engine sump oil
        // to maximum required volume.
        static
        const
        J1939_SPN           spn98 = {
            98,
            0,
            NULL    /*&percent01*/,
            "Engine Oil Level"
        };
        
        
        // SPN 99 - Engine Oil Filter Differential Pressure - Change in engine oil
        // pressure, measured across the filter, due to the filter and any accumulation
        // of solid or semisolid material on or in the filter.
        static
        const
        J1939_SPN           spn99 = {
            99,
            0,
            NULL    /*&pressure01*/,
            "Engine Oil Filter Differential Pressure"
        };
        
        
        // SPN 102 - Boost Pressure - Gage pressure of air measured downstream on the
        // compressor discharge side of the turbocharger. See also SPNs 1127-1130 for
        // alternate range and resolution. If there is one boost pressure to report
        // and this range and resolution is adequate, this parameter should be used.
        static
        const
        J1939_SPN           spn102 = {
            102,
            0,
            NULL    /*&pressure02*/,
            "Boost Pressure"
        };
        
        
        // SPN 108 - Barometric Pressure
        static
        const
        J1939_SPN           spn108 = {
            108,
            0,
            NULL    /*&???*/,
            "Barometric Pressure"
        };
        
        
        // SPN 110 - Engine Coolant Temperature - Temperature of liquid found in engine
        // cooling system.
        static
        const
        J1939_SPN           spn110 = {
            110,
            0,
            NULL    /*&temp01*/,
            "Engine Coolant Temperature"
        };
        
        
        // SPN 114 - Net Battery Current
        static
        const
        J1939_SPN           spn114 = {
            114,
            0,
            NULL    /*&???*/,
            "Net Battery Current"
        };
        
        
        // SPN 115 - Alternator Current
        static
        const
        J1939_SPN           spn115 = {
            115,
            0,
            NULL    /*&???*/,
            "Alternator Current"
        };
        
        
        // SPN 123 - Clutch Pressure
        static
        const
        J1939_SPN           spn123 = {
            123,
            0,
            NULL    /*&???*/,
            "Clutch Pressure"
        };
        
        
        // SPN 124 - Transmission Oil Level
        static
        const
        J1939_SPN           spn124 = {
            124,
            0,
            NULL    /*&???*/,
            "Transmission Oil Level"
        };
        
        
        // SPN 126 - Transmission Filter Differential Pressure
        static
        const
        J1939_SPN           spn126 = {
            126,
            0,
            NULL    /*&???*/,
            "Transmission Filter Differential Pressure"
        };
        
        
        // SPN 127 - Transmission Oil Pressure
        static
        const
        J1939_SPN           spn127 = {
            127,
            0,
            NULL    /*&???*/,
            "Transmission Oil Pressure"
        };
        
        
        // SPN 158 - Battery Potential (Voltage), Switched
        static
        const
        J1939_SPN           spn158 = {
            158,
            0,
            NULL    /*&???*/,
            "Battery Potential (Voltage), Switched"
        };
        
        
        // SPN 167 - Charging System Potential (Voltage)
        static
        const
        J1939_SPN           spn167 = {
            167,
            0,
            NULL    /*&???*/,
            "Charging System Potential (Voltage)"
        };
        
        
        // SPN 168 - Electrical Potential (Voltage)
        static
        const
        J1939_SPN           spn168 = {
            168,
            0,
            NULL    /*&???*/,
            "Electrical Potential (Voltage)"
        };
        
        
        // SPN 170 - Cab Interior Temperature
        static
        const
        J1939_SPN           spn170 = {
            170,
            0,
            NULL    /*&temp01*/,
            "Cab Interior Temperature"
        };
        
        
        // SPN 171 - Ambient Air Temperature
        static
        const
        J1939_SPN           spn171 = {
            171,
            0,
            NULL    /*&temp01*/,
            "Ambient Air Temperature"
        };
        
        
        // SPN 172 - Engine Air Inlet Temperature
        static
        const
        J1939_SPN           spn172 = {
            172,
            0,
            NULL    /*&temp01*/,
            "Engine Air Inlet Temperature"
        };
        
        
        // SPN 174 - Fuel Temperature - Temperature of fuel entering injectors.
        static
        const
        J1939_SPN           spn174 = {
            174,
            0,
            NULL    /*&temp01*/,
            "Fuel Temperature"
        };
        
        
        // SPN 175 - Engine Oil Temperature 1 - Temperature of the engine lubricant.
        static
        const
        J1939_SPN           spn175 = {
            175,
            0,
            NULL    /*&temp02*/,
            "Engine Oil Temperature 1"
        };
        
        
        // SPN 176 - Turbo Oil Temperature - Temperature of the turbocharger lubricant.
        static
        const
        J1939_SPN           spn176 = {
            176,
            0,
            NULL    /*&temp02*/,
            "Turbo Oil Temperature"
        };
        
        
        // SPN 177 - Transmission Oil Temperature
        static
        const
        J1939_SPN           spn177 = {
            177,
            0,
            NULL    /*&???*/,
            "Transmission Oil Temperature"
        };
        
        
        // SPN 190 - Engine Speed - Actual engine speed which is calculated over a
        // minimum crankshaft angle of 720 degrees divided by the number of cylinders.
        static
        const
        J1939_SPN           spn190 = {
            190,
            0,
            NULL    /*&velocityRotational01*/,
            "Engine Speed"
        };
        
        
        // SPN 234 - Software Identification Field
        // Delimited by '*'
        static
        const
        J1939_SPN           spn234 = {
            234,
            0,
            NULL    /*&????*/,
            "Software Identification Field"
        };
        
        
        // SPN 512 - Driver's Demand Engine - Percent Torque - The requested torque
        // output of the engine by the driver. It is based on input from the following
        // requestors external to the powertrain: operator (via the accelerator pedal),
        // cruise control and/or road speed limit governor. Dynamic commands from inter-
        // nal powertrain functions such as smoke control, low- and high-speed engine
        // governing; ASR and shift control are excluded from this calculation. The
        // data is transmitted in indicated torque as a percent of the reference engine
        // torque. See PGN 65251 for the engine configuration message. Several status
        // bits are defined separately to indicate the request which is currently being
        // honored. This parameter may be used for shift scheduling.
        static
        const
        J1939_SPN           spn512 = {
            512,
            0,
            NULL    /*&percent02*/,
            "Driver's Demand Engine - Percent Torque"
        };
        
        
        // SPN 513 - Actual Engine - Percent Torque - The calculated output
        // torque of the engine. The data is transmitted in indicated torque as a
        // percent of reference engine torque (see the engine configuration message,
        // PGN 65251). The engine percent torque value will not be less than zero and
        // it includes the torque developed in the cylinders required to overcome
        // friction.
        static
        const
        J1939_SPN           spn513 = {
            513,
            0,
            NULL    /*&percent02*/,
            "Actual Engine - Percent Torque"
        };
        
        
        // SPN 527 - Cruise Control States
        // 000 Off/Disabled
        // 001 Hold
        // 010 Accelerate
        // 011 Decelerate
        // 100 Resume
        // 101 Set
        // 110 Accelerator Override
        // 111 Not available
        static
        const
        J1939_SPN           spn527 = {
            527,
            0,
            NULL    /*&????*/,
            "Cruise Control States"
        };
        
        
        // SPN 558 - Accelerator Pedal 1 Low Idle Switch - Switch signal
        // which indicates the state of the accelerator pedal 1 low idle switch.
        // The low idle switch is defined in SAE J1843.
        // 00 Accelerator pedal 1 not in low idle condition
        // 01 Accelerator pedal 1 in low idle condition
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn558 = {
            558,
            0,
            NULL    /*&bits02*/,
            "Accelerator Pedal 1 Low Idle Switch"
        };
        
        
        // SPN 559 - Accelerator Pedal Kickdown Switch - Switch signal which
        // indicates whether the accelerator pedal kickdown switch is opened
        // or closed. The kickdown switch is defined in SAE J1843.
        // 00 Kickdown passive
        // 01 Kickdown active
        static
        const
        J1939_SPN           spn559 = {
            559,
            0,
            NULL    /*&bits01*/,
            "Accelerator Pedal Kickdown Switch"
        };
        
        
        // SPN 590 - Engine Idle Shutdown Timer State
        // 00 Inactive
        // 01 Active
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn590 = {
            590,
            0,
            NULL    /*&????*/,
            "Engine Idle Shutdown Timer State"
        };
        
        
        // SPN 591 - Engine Idle Shutdown Timer Function
        // 00  Disabled in calibration
        // 01  Enabled in calibration
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn591 = {
            591,
            0,
            NULL    /*&????*/,
            "Engine Idle Shutdown Timer Function"
        };
        
        
        // SPN 592 - Engine Idle Shutdown Timer Override
        // 00 Inactive
        // 01 Active
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn592 = {
            592,
            0,
            NULL    /*&????*/,
            "Engine Idle Shutdown Timer Override"
        };
        
        
        // SPN 593 - Engine Idle Shutdown has Shutdown Engine
        // 00 No
        // 01 Yes
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn593 = {
            593,
            0,
            NULL    /*&????*/,
            "Engine Idle Shutdown has Shutdown Engine"
        };
        
        
        // SPN 594 - Engine Idle Shutdown Driver Alert Mode
        // Status signal which indicates the status of the driver alert mode
        // of the idle shutdown timer system. While the driver alert mode is
        // active, the idle shutdown timer may be overridden.
        // 00 Inactive
        // 01 Active
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn594 = {
            594,
            0,
            NULL    /*&????*/,
            "Engine Idle Shutdown Driver Alert Mode"
        };
        
        
        // SPN 595 - Engine Idle Shutdown has Shutdown Engine
        // 00 Cruise control switched off
        // 01 Cruise control switched on
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn595 = {
            595,
            0,
            NULL    /*&????*/,
            "Cruise Control Active"
        };
        
        
        // SPN 596 - Cruise Control Enable Switch
        // 00 Cruise control disabled
        // 01 Cruise control enabled
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn596 = {
            596,
            0,
            NULL    /*&????*/,
            "Cruise Control Enable Switch"
        };
        
        
        // SPN 597 - Brake Switch
        // 00 Brake pedal released
        // 01 Brake pedal depressed
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn597 = {
            597,
            0,
            NULL    /*&????*/,
            "Brake Switch"
        };
        
        
        // SPN 598 - Clutch Switch
        // 00 Clutch pedal released
        // 01 Clutch pedal depressed
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn598 = {
            598,
            0,
            NULL    /*&????*/,
            "Clutch Switch"
        };
        
        
        // SPN 599 - Cruise Control Set Switch
        // 00 Cruise control activator not in the position “set”
        // 01 Cruise control activator in position “set”
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn599 = {
            599,
            0,
            NULL    /*&????*/,
            "Cruise Control Set Switch"
        };
        
        
        // SPN 600 - Cruise Control Coast (Decelerate) Switch
        // 00 Cruise control activator not in the position “coast”
        // 01 Cruise control activator in position “coast”
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn600 = {
            600,
            0,
            NULL    /*&????*/,
            "Cruise Control Coast (Decelerate) Switch"
        };
        
        
        // SPN 601 - Cruise Control Resume Switch
        // 00 Cruise control activator not in the position “resume”
        // 01 Cruise control activator in position “resume”
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn601 = {
            601,
            0,
            NULL    /*&????*/,
            "Cruise Control Resume Switch"
        };
        
        
        // SPN 602 - Cruise Control Accelerate Switch
        // 00 Cruise control activator not in the position “accelerate”
        // 01 Cruise control activator in position “accelerate”
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn602 = {
            602,
            0,
            NULL    /*&????*/,
            "Cruise Control Accelerate Switch"
        };
        
        
        // SPN 605 - Refrigerant High Pressure Switch
        // 00 Pressure normal
        // 01 Pressure too high, compressor clutch may be disengaged
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn605 = {
            605,
            0,
            NULL    /*&????*/,
            "Refrigerant High Pressure Switch"
        };
        
        
        // SPN 875 - Refrigerant Low Pressure Switch
        // 00 Pressure normal
        // 01 Pressure too low, compressor clutch may be disengaged
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn875 = {
            875,
            0,
            NULL    /*&????*/,
            "Refrigerant Low Pressure Switch"
        };
        
        
        // SPN 899 - Engine Torque Mode - State signal which indicates which
        // engine torque mode is currently generating, limiting, or controlling
        // the torque. Note that the modes are not in prioritized order. Not all
        // modes may be relevant for a given device. Some devices may not implement
        // all functions. For typical priorities refer to Figures SPN512_A and
        // SPN512_B for engine control and Tables SPN518_A to SPN518_B for retarder
        // control. The data type of this parameter is measured.
        // Mode 0000b means 'No request': engine torque may range from 0 to full load
        //             only due to low idle governor output; retarder torque == 0
        //              (no braking).
        // Modes 0001b to 1110b indicate that there is either a torque request or
        //              the identified function is currently controlling the engine/
        //              retarder: engine/retarder torque may range from 0 (no fueling/
        //              no braking) to the upper limit.
        static
        const
        J1939_SPN           spn899 = {
            899,
            0,
            NULL    /*&bits03*/,
            "Engine Torque Mode"
        };
        
        
        // SPN 917 - High Resolution Total Vehicle Distance
        static
        const
        J1939_SPN           spn917 = {
            917,
            0,
            NULL    /*&????*/,
            "High Resolution Total Vehicle Distance"
        };
        
        
        // SPN 918 - High Resolution Trip Distance
        static
        const
        J1939_SPN           spn918 = {
            918,
            0,
            NULL    /*&????*/,
            "High Resolution Trip Distance"
        };
        
        
        // SPN 965 - Number of Software Identification Fields
        static
        const
        J1939_SPN           spn965 = {
            965,
            0,
            NULL    /*&????*/,
            "Number of Software Identification Fields"
        };
        
        
        // SPN 966 - Engine Test Mode Switch
        // 00 Off
        // 01 On
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn966 = {
            966,
            0,
            NULL    /*&????*/,
            "Engine Test Mode Switch"
        };
        
        
        // SPN 967 - Engine Idle Decrement Switch
        // 00 Off
        // 01 On
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn967 = {
            967,
            0,
            NULL    /*&????*/,
            "Engine Idle Decrement Switch"
        };
        
        
        // SPN 968 - Engine Idle Increment Switch
        // 00 Off
        // 01 On
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn968 = {
            968,
            0,
            NULL    /*&????*/,
            "Engine Idle Increment Switch"
        };
        
        
        // SPN 969 - Remote Accelerator Enable Switch
        // 00 Off
        // 01 On
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn969 = {
            969,
            0,
            NULL    /*&????*/,
            "Remote Accelerator Enable Switch"
        };
        
        
        // SPN 974 - Remote Accelerator Pedal Position - The ratio of actual position
        // of the remote analog engine speed/torque request input device (such as an
        // accelerator pedal or throttle lever) to the maximum position of the input
        // device. For example, in on-highway vehicles this could be an accelerator
        // control device that is external to the drivers cab or an accelerator that
        // is controlled by a hand lever from the operators seat. The Remote Accelerator
        // Enable Switch is SPN 969. This parameter enables the remote accelerator
        // operation. NOTE: See SPNs 28, 29, and 91 for additional accelerator position
        // parameters. If only one accelerator position exists on a vehicle, SPN 91
        // shall be used.
        static
        const
        J1939_SPN           spn974 = {
            974,
            0,
            NULL    /*&percent01*/,
            "Remote Accelerator Pedal Position"
        };
        
        
        // SPN 976 - PTO State
        // 00000 Off/Disabled
        // 00001 Hold
        // 00010 Remote Hold
        // 00011 Standby
        // 00100 Remote Standby
        // 00101 Set
        // 00110 Decelerate/Coast
        // 00111 Resume
        // 01000 Accelerate
        // 01001 Accelerator Override
        // 01010 Preprogrammed set speed 1
        // 01011 Preprogrammed set speed 2
        // 01100 Preprogrammed set speed 3
        // 01101 Preprogrammed set speed 4
        // 01110 Preprogrammed set speed 5
        // 01111 Preprogrammed set speed 6
        // 10000 Preprogrammed set speed 7
        // 10001 Preprogrammed set speed 8
        // 10010 PTO set speed memory 1
        // 10011 PTO set speed memory 2
        // 10100 Not defined
        // 10101 Not defined
        // 10110 Not defined
        // 10111 Not defined
        // 11110 Not defined
        // 11111 Not available
        static
        const
        J1939_SPN           spn976 = {
            976,
            0,
            NULL    /*&????*/,
            "PTO State"
        };
        
        
        // SPN 985 - A/C High Pressure Fan Switch
        // 00 Pressure normal
        // 01 Pressure too high, fan may be engaged
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn985 = {
            985,
            0,
            NULL    /*&????*/,
            "A/C High Pressure Fan Switch"
        };
        
        
        // SPN 986 - Requested Percent Fan Speed
        static
        const
        J1939_SPN           spn986 = {
            986,
            0,
            NULL    /*&????*/,
            "Requested Percent Fan Speed"
        };
        
        
        // SPN 1081 - Engine Wait to Start Lamp
        // Lamp signal which indicates that the engine is too cold to start
        // and the operator should wait until the signal becomes inactive
        // (turns off).
        // 00 Off
        // 01 On
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1081 = {
            1081,
            0,
            NULL    /*&????*/,
            "Engine Wait to Start Lamp"
        };
        
        
        // SPN 1107 - Engine Protection System Timer State
        // 00 Inactive
        // 01 Active
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1107 = {
            1107,
            0,
            NULL    /*&????*/,
            "Engine Protection System Timer State"
        };
        
        
        // SPN 1108 - Engine Protection System Timer Override
        // 00 Inactive
        // 01 Active
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1108 = {
            1107,
            0,
            NULL    /*&????*/,
            "Engine Protection System Timer Override"
        };
        
        
        // SPN 1109 - Engine Protection System Approaching Shutdown
        // 00 Not Approaching
        // 01 Approaching
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1109 = {
            1109,
            0,
            NULL    /*&????*/,
            "Engine Protection System Approaching Shutdown"
        };
        
        
        // SPN 1110 - Engine Protection System has Shutdown Engine
        // 00 No
        // 01 Yes
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1110 = {
            1110,
            0,
            NULL    /*&????*/,
            "Engine Protection System Timer State"
        };
        
        
        // SPN 1111 - Engine Protection System Configuration
        // 00 Disabled in calibration
        // 01 Enabled in calibration
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1111 = {
            1111,
            0,
            NULL    /*&????*/,
            "Engine Protection System Configuration"
        };
        
        
        // SPN 1134 - Engine Intercooler Thermostat Opening - The current position
        // of the thermostat used to regulate the temperature of the engine intercooler.
        // A value of 0% represents the thermostat being completely closed and 100%
        // represents the thermostat being completely open.
        static
        const
        J1939_SPN           spn1134 = {
            1134,
            0,
            NULL    /*&percent01*/,
            "Engine Intercooler Thermostat Opening"
        };
        
        
        // SPN 1237 - Engine Shutdown Override Switch
        // 00 Off
        // 01 On
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1237 = {
            1237,
            0,
            NULL    /*&????*/,
            "Engine Shutdown Override Switch"
        };
        
        
        // SPN 1437 - Road Speed Limit Status - Status (active or not active) of the
        // system used to limit maximum vehicle velocity.
        // 00 - Active
        // 01 - Not Active
        // NOTE - While somewhat inconsistent with other J1939 status parameters, the
        // states defining 00 = active and 01 = inactive for Road Speed Limit Status
        // are NOT typographical errors, and should be implemented as stated.
        static
        const
        J1939_SPN           spn1437 = {
            1437,
            0,
            NULL    /*&bits01*/,
            "Road Speed Limit Status"
        };
        
        
        // SPN 1480 - Source Address of Controlling Device for Retarder Control -
        // The source address of the SAE J1939 device currently controlling the
        // retarder. It is used to expand the torque mode parameter (see SPN 899)
        // in cases where control is in response to an ECU that is not listed in
        // Table SPN899_A. Its value may be the source address of the ECU trans-
        // mitting the message (which means that no external SAE J1939 message is
        // providing the active command) or the source address of the SAE J1939
        // ECU that is currently providing the active command in a TSC1 (see PGN 0)
        // or similar message. Note that if this parameter value is the same as
        // the source address of the device transmitting it, the control may be
        // due to a message on a non-SAE J1939 data link such as SAE J1922 or a
        // proprietary link.
        static
        const
        J1939_SPN           spn1480 = {
            1480,
            0,
            NULL    /*&sourceAddress*/,
            "Source Address of Controlling Device for Retarder Control"
        };
        
        
        // SPN 1481 - Source Address of Controlling Device for Brake Control -
        // The source address of the SAE J1939 device currently controlling the
        // brake system. Its value may be the source address of the ECU trans-
        // mitting the message (which means that no external SAE J1939 message
        // is providing the active command) or the source address of the SAE
        // J1939 ECU that is currently providing the active command in a TSC1
        // (see PGN 0) or similar message.
        // Note that if this parameter value is the same as the source address
        // of the device transmitting it, the control may be due to a message
        // on a non-SAE J1939 data link such as SAE J1922 or a proprietary link.
        static
        const
        J1939_SPN           spn1481 = {
            1481,
            0,
            NULL    /*&sourceAddress*/,
            "Source Address of Controlling Device for Brake Control"
        };
        
        
        // SPN 1482 - Source Address of Controlling Device for Transmission Control -
        // The source address of the SAE J1939 device currently controlling the
        // transmission. Its value may be the source address of the ECU transmitting
        // the message (which means that no external SAE J1939 message is providing
        // the active command) or the source address of the SAE J1939 ECU that is
        // currently providing the active command in a TSC1 (see PGN 0) or similar
        // message.
        // Note that if this parameter value is the same as the source address of the
        // device transmitting it, the control may be due to a message on a non-SAE
        // J1939 data link such as SAE J1922 or a proprietary link.
        static
        const
        J1939_SPN           spn1482 = {
            1482,
            0,
            NULL    /*&sourceAddress*/,
            "Source Address of Controlling Device for Transmission Control"
        };
        
        
        // SPN 1483 - Source Address of Controlling Device for Engine Control - The
        // source address of the SAE J1939 device currently controlling the engine.
        // It is used to expand the torque mode parameter (see SPN 899) in cases where
        // control is in response to an ECU that is not listed in Table SPN899_A. Its
        // value may be the source address of the ECU transmitting the message (which
        // means that no external SAE J1939 message is providing the active command)
        // or the source address of the SAE J1939 ECU that is currently providing the
        // active command in a TSC1 (see PGN 0) or similar message. Note that if this
        // parameter value is the same as the source address of the device transmitting
        // it, the control may be due to a message on a non-J1939 data link such as SAE
        // J1922 or a proprietary link.
        static
        const
        J1939_SPN           spn1483 = {
            1483,
            0,
            NULL    /*&sourceAddress*/,
            "Source Address of Controlling Device for Engine Control"
        };
        
        
        // SPN 1633 - Cruise Control Pause Switch -
        // 00 Off
        // 01 On
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1633 = {
            1633,
            0,
            NULL    /*&????*/,
            "Cruise Control Pause Switch"
        };
        
        
        // SPN 1636 - Intake Manifold 1 Air Temperature (High Resolution) - Temperature
        // of pre-combustion air found in intake manifold of engine air supply system.
        // The higher resolution is required for control purposes.
        static
        const
        J1939_SPN           spn1636 = {
            1636,
            0,
            NULL    /*&temp02*/,
            "Intake Manifold 1 Air Temperature (High Resolution)"
        };
        
        
        // SPN 1637 - Engine Coolant Temperature (High Resolution) - Temperature of
        // liquid found in engine cooling system. The higher resolution is required
        // for control purposes.
        static
        const
        J1939_SPN           spn1637 = {
            1637,
            0,
            NULL    /*&temp02*/,
            "Engine Coolant Temperature (High Resolution)"
        };
        
        
        // SPN 1653 - Vehicle Limiting Speed Governor Enable Switch
        // 00 Switch disabled
        // 01 Switch enabled
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1653 = {
            1653,
            0,
            NULL    /*&????*/,
            "Vehicle Limiting Speed Governor Enable Switch"
        };
        
        
        // SPN 1654 - Vehicle Limiting Speed Governor Increment Switch
        // 00 Switch in the off state
        // 01 Switch in the on state
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1654 = {
            1654,
            0,
            NULL    /*&????*/,
            "Vehicle Limiting Speed Governor Increment Switch"
        };
        
        
        // SPN 1655 - Vehicle Limiting Speed Governor Decrement Switch
        // Switch signal which decreases the Vehicle Limiting Speed Governor (VLSG).
        // 00 Switch in the off state
        // 01 Switch in the on state
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1655 = {
            1655,
            0,
            NULL    /*&????*/,
            "Vehicle Limiting Speed Governor Decrement Switch"
        };
        
        
        // SPN 1656 - Engine Automatic Start Enable Switch
        // Switch signal which enables the idle management system to be enabled. When
        // this system is enabled with the engine in an idle mode and safe operating
        // conditions existing, then the engine may be started or stopped automatically.
        // 00 Switch in the off state
        // 01 Switch in the on state
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1656 = {
            1656,
            0,
            NULL    /*&????*/,
            "Engine Automatic Start Enable Switch"
        };
        
        
        // SPN 1666 - Automatic Gear Shifting Enable Switch
        static
        const
        J1939_SPN           spn1666 = {
            1666,
            0,
            NULL    /*&????*/,
            "Automatic Gear Shifting Enable Switch"
        };
        
        
       // SPN 1675 - Engine Starter Mode - There are several phases in a
        // starting action and different reasons why a start cannot take place.
        // 0000 start not requested
        // 0001 starter active, gear not engaged
        // 0010 starter active, gear engaged
        // 0011 start finished; starter not active after having been actively engaged
        //      (after 50ms mode goes to 0000) 0100 starter inhibited due to engine
        //       already running)
        // 0101 starter inhibited due to engine not ready for start (preheating)
        // 0110 starter inhibited due to driveline engaged or other transmission inhibit
        // 0111 starter inhibited due to active immobilizer
        // 1000 starter inhibited due to starter over-temp
        // 1001-1011 Reserved
        // 1100 starter inhibited - reason unknown
        // 1101 error (legacy implementations only; use 1110)
        // 1110 error
        // 1111 not available
        static
        const
        J1939_SPN           spn1675 = {
            1675,
            0,
            NULL    /*&bits03*/,
            "Engine Starter Mode"
        };
        
        
        // SPN 1682 - Battery Main Switch Hold Request
        // 00 Release Battery Main Switch
        // 01 Hold Battery Main Switch
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1682 = {
            1682,
            0,
            NULL    /*&????*/,
            "Battery Main Switch Hold Request"
        };
        
        
        // SPN 1683 - Auxiliary Heater Mode Request
        // 0000 De-activate auxiliary heater
        // 0001 Off due to ADR per European Regulations for Transport of hazardous materials
        // 0010 Economy mode
        // 0011 Normal mode
        // 0100-1101 Not defined
        // 1110 Reserved
        // 1111 Don't care/take no action
        static
        const
        J1939_SPN           spn1683 = {
            1683,
            0,
            NULL    /*&????*/,
            "Auxiliary Heater Mode Request"
        };
        
        
        // SPN 1684 - Auxiliary Heater Coolant Pump Request
        // 00 Deactivate water pump
        // 01 Activate water pump
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1684 = {
            1684,
            0,
            NULL    /*&????*/,
            "Auxiliary Heater Coolant Pump Request"
        };
        
        
        // SPN 1685 - Request Engine Zone Heating
        // 00 Do not heat engine zone
        // 01 Heat engine zone
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1685 = {
            1685,
            0,
            NULL    /*&????*/,
            "Auxiliary Heater Coolant Pump Request"
        };
        
        
        // SPN 1686 - Request Cab Zone Heating
        // 00 Do not cab engine zone
        // 01 Heat cab zone
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1686 = {
            1686,
            0,
            NULL    /*&????*/,
            "Request Cab Zone Heating"
        };
        
        
        // SPN 1691 - Cab Interior Temperature Command
        static
        const
        J1939_SPN           spn1691 = {
            1691,
            0,
            NULL    /*&????*/,
            "Cab Interior Temperature Command"
        };
        
        
        // SPN 1714 - Operator Seat Direction Switch
        // 00 Operator seat not facing forward
        // 01 Operator seat is facing forward
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1714 = {
            1714,
            0,
            NULL    /*&????*/,
            "Operator Seat Direction Switch"
        };
        
        
        // SPN 1856 - Seat Belt Switch
        // 00 NOT Buckled
        // 01 OK - Seat Belt is buckled
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1856 = {
            1856,
            0,
            NULL    /*&????*/,
            "Seat Belt Switch"
        };
        
        
        // SPN 2432 - Engine Demand - Percent Torque - The requested torque output of
        // the engine by all dynamic internal inputs, including smoke control, noise
        // control and low and high speed governing.
        static
        const
        J1939_SPN           spn2432 = {
            2432,
            0,
            NULL    /*&percent02*/,
            "Engine Demand - Percent Torque"
        };
        
        
        // SPN 2540 - Parameter Group Number (RQST)
        static
        const
        J1939_SPN           spn2540 = {
            2540,
            0,
            NULL    /*&????*/,
            "Parameter Group Number (RQST)"
        };
        
        
        // SPN 2550 - Manufacturer Specific Information (PropA_PDU1)
        //  Variable length data specified by manufacturer (0 to 1785 bytes)
        static
        const
        J1939_SPN           spn2550 = {
            2540,
            0,
            NULL    /*&????*/,
            "Manufacturer Specific Information (PropA_PDU1)"
        };
        
        
        // SPN 2574 - Parameter Group Number (RQST2)
        static
        const
        J1939_SPN           spn2574 = {
            2574,
            0,
            NULL    /*&????*/,
            "Parameter Group Number (RQST2)"
        };
        
        
        // SPN 2575 - Use Transfer Mode
        // 00 No
        // 01 Yes
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn2575 = {
            2575,
            0,
            NULL    /*&????*/,
            "Use Transfer Mode"
        };
        
        
       // SPN 2596 - Selected Maximum Vehicle Speed Limit
        static
        const
        J1939_SPN           spn2596 = {
            2596,
            0,
            NULL    /*&????*/,
            "Selected Maximum Vehicle Speed Limit"
        };
        
        
        // SPN 2812 - Engine Overspeed Test
        // 00 Engine Overspeed Test Not Active
        // 01 Engine Overspeed Test Active
        // 10 Reserved
        // 11 Not available
        static
        const
        J1939_SPN           spn2812 = {
            2812,
            0,
            NULL    /*&????*/,
            "Engine Overspeed Test"
        };
        
        
        // SPN 2813 - Engine Air Shutoff Command Status
        // 00 No
        // 01 Yes
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn2813 = {
            2813,
            0,
            NULL    /*&????*/,
            "Engine Air Shutoff Command Status"
        };
        
        
        // SPN 2814 - Engine Overspeed Test
        // 00 Disabled
        // 01 Enabled
        // 10 Reserved
        // 11 Not available
        static
        const
        J1939_SPN           spn2814 = {
            2814,
            0,
            NULL    /*&????*/,
            "Engine Overspeed Test"
        };
        
        
        // SPN 2815 - Engine Alarm Output Command Status
        // 00 Engine Alarm Output Command Not Active
        // 01 Engine Alarm Output Command Active
        // 10 Reserved
        // 11 Not available
        static
        const
        J1939_SPN           spn2815 = {
            2815,
            0,
            NULL    /*&????*/,
            "Engine Alarm Output Command Status"
        };
        
        
        // SPN 2848 - Engine Demand - Percent Torque - The requested torque output of
        static
        const
        J1939_SPN           spn2848 = {
            2848,
            0,
            NULL    /*&bits64*/,
            ""
        };
        
        
        // SPN 3026 - Transmission Oil Level Measurement Status
        static
        const
        J1939_SPN           spn3026 = {
            3026,
            0,
            NULL    /*&???*/,
            "Transmission Oil Level Measurement Status"
        };
        
        
        // SPN 3027 - Transmission Oil Level High / Low
        static
        const
        J1939_SPN           spn3027 = {
            3027,
            0,
            NULL    /*&???*/,
            "Transmission Oil Level High / Low"
        };
        
        
        // SPN 3028 - Transmission Oil Level Countdown Timer
        static
        const
        J1939_SPN           spn3028 = {
            3028,
            0,
            NULL    /*&???*/,
            "Transmission Oil Level Countdown Timer"
        };
        
        

        
        static
        const
        J1939_PGNSPN        pgn51456spns[2] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 51456, 2574,  24,    0,     0,    0,  &spn2574 },
            { 51456, 2575,   2,    0,     3,    0,  &spn2575 }
        };
        
        
        static
        const
        J1939_PGNSPN        pgn57344spns[15] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 57344,  986,   8,    0,     0,    0,  &spn986 },
            { 57344, 1691,  16,    0,     2,    0,  &spn1691 },
            { 57344, 1684,   2,    0,     3,    0,  &spn1684 },
            { 57344, 1682,   2,    2,     3,    0,  &spn1682 },
            { 57344, 1714,   2,    4,     3,    0,  &spn1714 },
            { 57344, 1856,   2,    6,     3,    0,  &spn1856 },
            { 57344, 1655,   2,    2,     4,    0,  &spn1655 },
            { 57344, 1654,   2,    4,     4,    0,  &spn1654 },
            { 57344, 1653,   2,    6,     4,    0,  &spn1653 },
            { 57344, 1666,   2,    4,     5,    0,  &spn1666 },
            { 57344, 1656,   2,    6,     5,    0,  &spn1656 },
            { 57344, 1683,   2,    0,     6,    0,  &spn1683 },
            { 57344, 1685,   2,    4,     6,    0,  &spn1685 },
            { 57344, 1686,   2,    6,     6,    0,  &spn1686 },
            { 57344, 2596,   8,    0,     7,    0,  &spn2596 }
        };
        
        
        static
        const
        J1939_PGNSPN        pgn60928spns[1] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 60928, 2848,   0,    0,     0,     0, &spn2848 }
        };
        
        static
        const
        J1939_PGNSPN        pgn61184spns[1] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 61184, 2550,   0,    0,     0,     0, &spn2550 }
        };
        
       static
        const
        J1939_PGNSPN        pgn61443spns[6] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 61443,  558,   0,    0,     0,     0, &spn558 },
            { 61443,  559,   0,    0,     0,     0, &spn559 },
            { 61443, 1437,   0,    0,     0,     0, &spn1437 },
            { 61443,   91,   1,    0,     0,     0, &spn91 },
            { 61443,   92,   2,    0,     0,     0, &spn92 },
            { 61443,  974,   3,    0,     0,     0, &spn974 }
        };
        
        static
        const
        J1939_PGNSPN        pgn61444spns[7] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 61444,  899,   0,    0,     0,    0,  &spn899 },
            { 61444,  512,   1,    0,     0,    0,  &spn512 },
            { 61444,  513,   2,    0,     0,    0,  &spn513 },
            { 61444,  190,   3,    0,     0,    0,  &spn190 },
            { 61444, 1483,   5,    0,     0,    0,  &spn1483 },
            { 61444, 1675,   6,    0,     0,    0,  &spn1675 },
            { 61444, 2432,   7,    0,     0,    0,  &spn2432 }
        };
        
        static
        const
        J1939_PGNSPN        pgn65129spns[2] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65129, 1636,   0,    0,     0,    0,  &spn1636 },
            { 65129, 1637,   2,    0,     0,    0,  &spn1637 }
        };
        

        static
        const
        J1939_PGNSPN        pgn65217spns[2] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65217,  917,  32,    0,     0,    0,  &spn917 },
            { 65217,  918,  32,    0,     4,    0,  &spn918 }
        };
        
        static
        const
        J1939_PGNSPN        pgn65242spns[2] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65242,  965,   8,    0,     0,    0,  &spn965 },
            { 65242,  234,   0,    0,     0,    0,  &spn234 }
        };
        
        
        static
        const
        J1939_PGNSPN        pgn65252spns[18] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65252,  593,   2,    0,     0,    0,  &spn593 },
            { 65252,  594,   2,    2,     0,    0,  &spn594 },
            { 65252,  592,   2,    4,     0,    0,  &spn592 },
            { 65252,  590,   2,    6,     0,    0,  &spn590 },
            { 65252,  591,   2,    6,     1,    0,  &spn591 },
            { 65252,  985,   2,    0,     2,    0,  &spn985 },
            { 65252,  875,   2,    2,     2,    0,  &spn875 },
            { 65252,  605,   2,    4,     2,    0,  &spn605 },
            { 65252, 1081,   2,    0,     3,    0,  &spn1081 },
            { 65252, 1110,   2,    0,     4,    0,  &spn1110 },
            { 65252, 1109,   2,    2,     4,    0,  &spn1109 },
            { 65252, 1108,   2,    4,     4,    0,  &spn1108 },
            { 65252, 1107,   2,    6,     4,    0,  &spn1107 },
            { 65252, 1111,   2,    6,     5,    0,  &spn1111 },
            { 65252, 2815,   2,    0,     6,    0,  &spn2815 },
            { 65252, 2814,   2,    2,     6,    0,  &spn2814 },
            { 65252, 2813,   2,    4,     6,    0,  &spn2813 },
            { 65252, 2812,   2,    6,     6,    0,  &spn2812 }
        };
        
        
        static
        const
        J1939_PGNSPN        pgn65261spns[3] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65261,  110,   8,    0,     0,    0,  &spn74 },
            { 65261,  174,   8,    0,     1,    0,  &spn87 },
            { 65261,  175,   8,    0,     2,    0,  &spn88 }
        };
        
        
        static
        const
        J1939_PGNSPN        pgn65262spns[6] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65262,  110,   0,    0,     0,    0,  &spn110 },
            { 65262,  174,   1,    0,     0,    0,  &spn174 },
            { 65262,  175,   2,    0,     0,    0,  &spn175 },
            { 65262,  176,   3,    0,     0,    0,  &spn176 },
            { 65262,   52,   6,    0,     0,    0,  &spn52 },
            { 65262, 1134,   7,    0,     0,    0,  &spn1134 }
        };
        

        static
        const
        J1939_PGNSPN        pgn65265spns[19] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65265,   69,   2,    0,     0,    0,  &spn69 },
            { 65265,   70,   2,    2,     0,    0,  &spn70 },
            { 65265, 1633,   2,    4,     0,    0,  &spn1633 },
            { 65265,   84,  16,    0,     2,    0,  &spn84 },
            { 65265,  595,   2,    0,     3,    0,  &spn595 },
            { 65265,  596,   2,    2,     3,    0,  &spn596 },
            { 65265,  597,   2,    4,     3,    0,  &spn597 },
            { 65265,  598,   2,    6,     3,    0,  &spn598 },
            { 65265,  599,   2,    0,     4,    0,  &spn599 },
            { 65265,  600,   2,    2,     4,    0,  &spn600 },
            { 65265,  601,   2,    4,     4,    0,  &spn601 },
            { 65265,  602,   2,    6,     4,    0,  &spn602 },
            { 65265,   86,   8,    6,     5,    0,  &spn86 },
            { 65265,  976,   5,    0,     6,    0,  &spn976 },
            { 65265,  527,   3,    5,     6,    0,  &spn527 },
            { 65265,  968,   2,    0,     7,    0,  &spn968 },
            { 65265,  967,   2,    2,     7,    0,  &spn967 },
            { 65265,  966,   2,    4,     7,    0,  &spn966 },
            { 65265, 1237,   2,    6,     7,    0,  &spn1237 }
        };
        
        
        static
        const
        J1939_PGNSPN        pgn65269spns[5] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65269,  108,   0,    0,     0,    0,  &spn108 },
            { 65269,  170,   1,    0,     0,    0,  &spn170 },
            { 65269,  171,   2,    0,     0,    0,  &spn171 },
            { 65269,  172,   3,    0,     0,    0,  &spn172 },
            { 65269,   79,   6,    0,     0,    0,  &spn79 }
        };
        
        
        static
        const
        J1939_PGNSPN        pgn65271spns[5] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65271,  114,   8,    0,     0,    0,  &spn114 },
            { 65271,  115,   8,    0,     1,    0,  &spn115 },
            { 65271,  167,  16,    0,     3,    0,  &spn167 },
            { 65271,  168,  16,    0,     5,    0,  &spn168 },
            { 65271,  158,  16,    0,     7,    0,  &spn158 }
        };
        
        
        static
        const
        J1939_PGNSPN        pgn65272spns[8] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65272,  123,   8,    0,     0,    0,  &spn123 },
            { 65272,  124,   8,    0,     1,    0,  &spn124 },
            { 65272,  126,   8,    0,     2,    0,  &spn126 },
            { 65272,  127,   8,    0,     3,    0,  &spn127 },
            { 65272,  177,  16,    0,     5,    0,  &spn177 },
            { 65272, 3027,   8,    0,     6,    0,  &spn3027 },
            { 65272, 3028,   4,    0,     7,    0,  &spn3028 },
            { 65272, 3026,   4,    4,     7,    0,  &spn3026 }
        };
        
        
        
        
        
        const
        J1939_PGN_ENTRY     pgn0_entry = {
            // PGN 0  0x000000 - Torque/Speed Control 1 - TSC1
            0x00000000,
            50,                 // msFreq (to Retarder)(10ms to Engine)
            8,                  // dlc
            3,                  // priority
            7,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn256_entry = {
            // PGN 0  0x000100 - Transmission Control 1 - TC1
            0x00000100,
            50,                 // msFreq (only when active)
            8,                  // dlc
            3,                  // priority
            17,                 // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn51456_entry = {
            // PGN 51456  0x00C900 - Request2
            0x0000C900,
            0,                  // msFreq
            8,                  // dlc
            6,                  // priority
            2,                  // cSPNs
            0,                  // --reserved--
            pgn51456spns,       // SPN Table Pointer
            "Request2"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn57344_entry = {
            // PGN 57344  0x00E000 - Cab Message 1 - CM1
            0x0000FEEE,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            15,                  // cSPNs
            0,                  // --reserved--
            pgn57344spns,       // SPN Table Pointer
            "Cab Message 1 - CM1"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn59392_entry = {
            // PGN 59392  0x00E800 - ACK/NAK
            0x0000E800,
            0,                  // msFreq
            8,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn59904_entry = {
            // PGN 59904  0x00EA00 (PDU1) - Request for PGN
            0x0000EA00,
            0,                  // msFreq
            3,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn60160_entry = {
            // PGN 60160  0x00EC00 - Transport Protocol - Data Transfer
            0x0000EB00,
            0,                  // msFreq
            8,                  // dlc
            7,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL,               // SPN Table Pointer
            "Transport Protocol - Data Transfer"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn60416_entry = {
            // PGN 60416  0x00EC00 - Transport Protocol - Connection Management
            0x0000EC00,
            0,                  // msFreq
            8,                  // dlc
            7,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL,               // SPN Table Pointer
            "Transport Protocol - Connection Management"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn60928_entry = {
            // PGN 60928  0x00EE00 - Claim Address/Cannot Claim Address
            0x0000EE00,
            0,                  // msFreq
            8,                  // dlc
            6,                  // priority
            1,                  // cSPNs
            0,                  // --reserved--
            pgn60928spns,       // SPN Table Pointer
            "Claim Address/Cannot Claim Address"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61184_entry = {
            // PGN 61184  0x00EF00 - Proprietary A
            0x0000EF00,
            0,                  // msFreq
            0,                  // dlc  - variable up to 1785
            6,                  // priority
            0,                  // cSPNs                (No SAE defined SPNs)
            0,                  // --reserved--
            NULL                // SPN Table Pointer    (No SAE defined SPNs)
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61440_entry = {
            // PGN 61440  0x00F000 - Electronic Retarder Controller 1 - ERC1
            0x0000F000,
            100,                // msFreq
            8,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61442_entry = {
            // PGN 61442  0x00F002 - Electronic Transmission Controller 1 - ETC1
            0x0000F002,
            10,                 // msFreq
            8,                  // dlc
            3,                  // priority
            9,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61443_entry = {
            // PGN 61443  0x00F003 - Electronic Engine Controller 2 - EEC2
            0x0000F003,
            50,                 // msFreq
            8,                  // dlc
            3,                  // priority
            6,                  // cSPNs
            0,                  // --reserved--
            pgn61443spns,       // SPN Table Pointer
            "Electronic Engine Controller 2 - EEC2"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61444_entry = {
            // PGN 61444  0x00F004 - Electronic Engine Controller 1 - EEC1
            0x0000F004,
            100,                // msFreq
            8,                  // dlc
            3,                  // priority
            7,                  // cSPNs
            0,                  // --reserved--
            pgn61444spns,       // SPN Table Pointer
            "Electronic Engine Controller 1 - EEC1"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61445_entry = {
            // PGN 61445  0x00F005 - Electronic Transmission Controller 1 - ETC2
            0x0000F005,
            100,                // msFreq
            8,                  // dlc
            6,                  // priority
            5,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65098_entry = {
            // PGN 65098  0x00FE4A - Electronic Transmission Controller 7 - ETC7
            0x0000FE4A,
            100,                // msFreq
            8,                  // dlc
            6,                  // priority
            11,                 // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65129_entry = {
            // PGN 65129  0x00FE69 - Engine Temperature 3 - ET3
            0x0000FE69,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            2,                  // cSPNs
            0,                  // --reserved--
            pgn65129spns,       // SPN Table Pointer
            "Engine Temperature 3 - ET3"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65217_entry = {
            // PGN 65217  0x00FEC1 - High Resolution Vehicle Distance - VDHR
            0x0000FEC1,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            2,                  // cSPNs
            0,                  // --reserved--
            pgn65217spns,       // SPN Table Pointer
            "High Resolution Vehicle Distance - VDHR"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65226_entry = {
            // PGN 65226  0x00FECA - Active Diagnostic Trouble Codes - DM1
            0x0000FECA,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65242_entry = {
            // PGN 65242  0x00FEDA - Software Identification - SOFT
            0x0000FEDA,
            0,                  // msFreq - on demand
            0,                  // dlc - variable up to 201
            6,                  // priority
            2,                  // cSPNs
            0,                  // --reserved--
            pgn65242spns,       // SPN Table Pointer
            "Software Identification - SOFT"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65247_entry = {
            // PGN 65247  0x00FEDF - Electronic Engine Controller 3 - EEC3
            0x0000FEDF,
            250,                // msFreq
            8,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65249_entry = {
            // PGN 65249  0x00FEE1 - Retarder Configuration - RC -
            0x00FEE1,
            5000,               // msFreq
            19,                 // dlc
            6,                  // priority
            14,                 // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65251_entry = {
            // PGN 65251  0x00FEE3 - Engine Configuration 1 - EC1 -
            0x00FEE1,
            5000,               // msFreq
            39,                 // dlc
            6,                  // priority
            14,                 // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65252_entry = {
            // PGN 65252  0x00FEE4 - Shutdown           - SHUTDOW -
            0x00FEE4,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            18,                 // cSPNs
            0,                  // --reserved--
            pgn65252spns,       // SPN Table Pointer
            "Shutdown - SHUTDOW"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65261_entry = {
            // PGN 65261  0x00FEED - CruiseControl/VehicleSpeedSetup - CCSS
            0x0000FEED,
            0,                  // msFreq
            8,                  // dlc
            6,                  // priority
            3,                  // cSPNs
            0,                  // --reserved--
            pgn65265spns        // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65262_entry = {
            // PGN 65262  0x00FEEE - Engine Temperature 1 - ET1
            0x0000FEEE,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            6,                  // cSPNs
            0,                  // --reserved--
            pgn65262spns,       // SPN Table Pointer
            "Engine Temperature 1 - ET1"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65265_entry = {
            // PGN 65265  0x00FEF1 - Cruise Control/Vehicle Speed - CCVS
            0x0000FEF1,
            100,                // msFreq
            8,                  // dlc
            6,                  // priority
            19,                 // cSPNs
            0,                  // --reserved--
            pgn65265spns        // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65269_entry = {
            // PGN 65269  0x00FEF5 - Ambient Conditions - AMB
            0x0000FEF5,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            5,                  // cSPNs
            0,                  // --reserved--
            pgn65269spns        // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65271_entry = {
            // PGN 65271  0x00FEF7 - Vehicle Electrical Power #1 - VEP1
            0x0000FEF7,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            5,                  // cSPNs
            0,                  // --reserved--
            pgn65271spns        // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65272_entry = {
            // PGN 65272  0x00FEF8 - Transmission Fluids 1 - TRF1
            0x0000FEF8,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            8,                  // cSPNs
            0,                  // --reserved--
            pgn65272spns        // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     *pgn_index[] = {
            &pgn0_entry,
            &pgn256_entry,
            &pgn51456_entry,
            &pgn57344_entry,
            &pgn59392_entry,
            &pgn59904_entry,
            &pgn60160_entry,
            &pgn60416_entry,
            &pgn60928_entry,
            &pgn61184_entry,
            &pgn61440_entry,
            &pgn61442_entry,
            &pgn61443_entry,
            &pgn61444_entry,
            &pgn61445_entry,
            &pgn65098_entry,
            &pgn65129_entry,
            &pgn65217_entry,
            &pgn65226_entry,
            &pgn65247_entry,
            &pgn65249_entry,
            &pgn65261_entry,
            &pgn65262_entry,
            &pgn65265_entry,
            &pgn65269_entry,
            &pgn65271_entry,
            &pgn65272_entry,
            NULL
        };
        
        
        const
        J1939_PGN_TABLE     pgn_table = {
            (sizeof(pgn_index)/sizeof(J1939_PGN_ENTRY *)) - 1,
            0,
            &pgn_index
        };
        
        
        
        


 
    /****************************************************************
    * * * * * * * * * * *  Internal Subroutines   * * * * * * * * * *
    ****************************************************************/



    /****************************************************************
    * * * * * * * * * * *  External Subroutines   * * * * * * * * * *
    ****************************************************************/


    //===============================================================
    //                      *** Class Methods ***
    //===============================================================

    J1939TBL_DATA * j1939tbl_Alloc(
    )
    {
        J1939TBL_DATA   *this;
        uint32_t        cbSize = sizeof(J1939TBL_DATA);
        
        // Do initialization.
        
        this = obj_Alloc( cbSize );
        
        // Return to caller.
        return this;
    }



    //---------------------------------------------------------------
    //                  SPN to Signed Value
    //---------------------------------------------------------------
    
    int32_t         j1939tbl_SpnToS32(
        J1939_SPN_TYPE  *pType,
        uint16_t        data
    )
    {
        int32_t         value = 0;
        
        if (pType) {
            // The order of operations is important since we are
            // working with integers.
            // We expand some of the more common multiplications
            // and divisions to save time.
            if (1 == pType->mult) {
                value = data;
            }
            else if (2 == pType->mult) {
                value = (data << 1);
            }
            else if (4 == pType->mult) {
                value = (data << 2);
            }
            else {
                value = (data * pType->mult);
            }
            value += pType->round;
            if (1 == pType->div)
                ;
            else if (2 == pType->div) {
                value >>= 1;
            }
            else if (4 == pType->div) {
                value >>= 2;
            }
            else {
                value /= pType->div;
            }
            value += pType->offset;
        }
        
        // Return to caller.
        return value;
    }
    
    
    
    

    //===============================================================
    //                      P r o p e r t i e s
    //===============================================================

    uint16_t        j1939tbl_getPriority(
        J1939TBL_DATA     *this
    )
    {

        // Validate the input parameters.
#ifdef NDEBUG
#else
        if( !j1939tbl_Validate( this ) ) {
            DEBUG_BREAK();
        }
#endif

        //return this->priority;
        return 0;
    }

    bool            j1939tbl_setPriority(
        J1939TBL_DATA     *this,
        uint16_t        value
    )
    {
#ifdef NDEBUG
#else
        if( !j1939tbl_Validate( this ) ) {
            DEBUG_BREAK();
        }
#endif
        //this->priority = value;
        return true;
    }



    uint32_t        j1939tbl_getSize(
        J1939TBL_DATA       *this
    )
    {
#ifdef NDEBUG
#else
        if( !j1939tbl_Validate( this ) ) {
            DEBUG_BREAK();
        }
#endif
        return 0;
    }



    

    //===============================================================
    //                          M e t h o d s
    //===============================================================


    //---------------------------------------------------------------
    //                        D e a l l o c
    //---------------------------------------------------------------

    void            j1939tbl_Dealloc(
        OBJ_ID          objId
    )
    {
        J1939TBL_DATA   *this = objId;

        // Do initialization.
        if (NULL == this) {
            return;
        }        
#ifdef NDEBUG
#else
        if( !j1939tbl_Validate(this) ) {
            DEBUG_BREAK();
            return;
        }
#endif

        obj_Dealloc(this);
        this = NULL;

        // Return to caller.
    }



    //---------------------------------------------------------------
    //                          I n i t
    //---------------------------------------------------------------

    J1939TBL_DATA *   j1939tbl_Init(
        J1939TBL_DATA       *this
    )
    {
        uint32_t        cbSize = sizeof(J1939TBL_DATA);
        
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        
        this = obj_Init( this, cbSize, OBJ_IDENT_J1939TBL );
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        obj_setVtbl(this, (OBJ_IUNKNOWN *)&j1939tbl_Vtbl);
        
        //this->stackSize = obj_getMisc1(this);

    #ifdef NDEBUG
    #else
        if( !j1939tbl_Validate(this) ) {
            DEBUG_BREAK();
            return OBJ_NIL;
        }
        //BREAK_NOT_BOUNDARY4(&cbp->thread);
    #endif

        return this;
    }

     

    //---------------------------------------------------------------
    //                      V a l i d a t e
    //---------------------------------------------------------------

    #ifdef NDEBUG
    #else
    bool            j1939tbl_Validate(
        J1939TBL_DATA      *this
    )
    {
        if(this) {
            if ( obj_IsKindOf(this, OBJ_IDENT_J1939TBL) )
                ;
            else
                return false;
        }
        else
            return false;
        if( !(obj_getSize(this) >= sizeof(J1939TBL_DATA)) )
            return false;

        // Return to caller.
        return true;
    }
    #endif


    
    
    
#ifdef	__cplusplus
}
#endif


