// vi:nu:et:sts=4 ts=4 sw=4 tw=90
/*
 * File:   j1939tbl.c
 *	Generated by Vogel 05/20/2015 11:48:08
 *
 * Created on December 30, 2014
 */

 
/*
 This is free and unencumbered software released into the public domain.
 
 Anyone is free to copy, modify, publish, use, compile, sell, or
 distribute this software, either in source code form or as a compiled
 binary, for any purpose, commercial or non-commercial, and by any
 means.
 
 In jurisdictions that recognize copyright laws, the author or authors
 of this software dedicate any and all copyright interest in the
 software to the public domain. We make this dedication for the benefit
 of the public at large and to the detriment of our heirs and
 successors. We intend this dedication to be an overt act of
 relinquishment in perpetuity of all present and future rights to this
 software under copyright law.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 
 For more information, please refer to <http://unlicense.org/>
 */




//*****************************************************************
//* * * * * * * * * * * *  Data Definitions   * * * * * * * * * * *
//*****************************************************************

/* Header File Inclusion */
#include "j1939tbl_internal.h"



#ifdef	__cplusplus
extern "C" {
#endif
    

    
#ifdef	__cplusplus
    extern	"C" {
#endif
        
        
#ifdef XYZZY
        
        const
        J1939_SPN_TYPE      SAEbs01 = {  // Bits/States
            86,             // SAE Type
            1,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            1,              // Operating Max
            0,              // Data Min
            1               // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs02 = {  // Bits/States
            87,             // SAE Type
            2,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            3,              // Operating Max
            0,              // Data Min
            3               // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs03 = {  // Bits/States
            88,             // SAE Type
            3,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            7,              // Operating Max
            0,              // Data Min
            7               // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs04 = {  // Bits/States
            89,             // SAE Type
            4,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            15,             // Operating Max
            0,              // Data Min
            15              // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs05 = {  // Bits/States
            90,             // SAE Type
            5,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            31,             // Operating Max
            0,              // Data Min
            31              // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs06 = {  // Bits/States
            91,             // SAE Type
            6,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            63,             // Operating Max
            0,              // Data Min
            63              // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs07 = {  // Bits/States
            92,             // SAE Type
            7,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            127,            // Operating Max
            0,              // Data Min
            127             // Data Max
        };
        
        const
        J1939_SPN_TYPE      SAEbs08 = {  // Bits/States
            93,             // SAE Type
            8,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            255,            // Operating Max
            0,              // Data Min
            255             // Data Max
        };
        
        
        const
        J1939_SPN_TYPE      SAEpc05 = {  // Percent %
            45,             // SAE Type
            8,              // Length in Bits
            0,              // Decimal places
            1,              // Mult
            1,              // Div
            -125,           // Offset
            0,              // Round
            -125,           // Operating Min
            125,            // Operating Max
            0,              // Data Min
            250             // Data Max
        };
        
        
        const
        J1939_SPN_TYPE      SAEpr07 = { // Pressure in Kpa
            53,             // SAE Type
            8,              // Length in Bits
            0,              // Decimal places
            2,              // Mult
            1,              // Div
            0,              // Offset
            0,              // Round
            0,              // Operating Min
            500,            // Operating Max
            0,              // Data Min
            250             // Data Max
        };
        
        
        static
        const
        J1939_SPN_TYPE      bits64 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            64,     1,     1,      0,     0,     0,     0,      0,     0
        };
        
        
        static
        const
        J1939_SPN_TYPE      percent01 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            8,     4,    10,      0,     2,     0,   100,      0,   250
        };
        
        static
        const
        J1939_SPN_TYPE      percent03 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            8,     1,     1,      0,     0,     0,   125,      0,   250
        };
        
        
        static
        const
        J1939_SPN_TYPE      pressure01 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            8,     5,    10,      0,     2,     0,   125,      0,   250
        };
        
        
        // Source Address (SA) for a device
        static
        const
        J1939_SPN_TYPE      sourceAddress = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            8,     1,     1,      0,     0,     0,   253,      0,   255
        };
        
        
        static
        const
        J1939_SPN_TYPE      temp01 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            8,     1,     1,    -40,     2,   -40,   210,      0,   250
        };
        
        static
        const
        J1939_SPN_TYPE      temp02 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            16,  3125, 10000,   -273,  5000,  -273,  1735,      0, 55520
        };
        
        
        static
        const
        J1939_SPN_TYPE      velocityRotational01 = {
        //  Len   Mult    Div  offset  round    min    max     min    max
            16,   125,  1000,      0,   500,     0,  8031,      0, 64255
        };
#endif
        
        
        // SPN 51 - Throttle Position - The position of the valve used to regulate
        // the supply of a fluid, usually air or fuel/air mixture, to an engine.
        // 0% represents no supply and 100% is full supply.
        static
        const
        J1939_SPN           spn51 = {
            51,
            0,
            NULL    /*&percent01*/,
            "Throttle Position"
        };
        
        
        // SPN 52 - Engine Intercooler Temperature - Temperature of liquid found in the
        // intercooler located after the turbocharger.
        static
        const
        J1939_SPN           spn52 = {
            52,
            0,
            NULL    /*&temp01*/,
            "Engine Intercooler Temperature"
        };
        
        
        // SPN 91 - Accelerator Pedal Position 1 - The ratio of actual position of the
        // analog engine speed/torque request input device (such as an accelerator pedal
        // or throttle lever) to the maximum position of the input device. This parameter
        // is intended for the primary accelerator control in an application. If an appli-
        // cation has only one accelerator control, use SPN 91. For on-highway vehicles,
        // this will typically be the operator's accelerator pedal. Although it is used
        // as an input to determine powertrain demand, it also provides anticipatory
        // information to transmission and ASR algorithms about driver actions. In marine
        // applications, this will typically be the operator's throttle lever. If a low
        // idle validation switch is used in conjunction with accelerator pedal position
        // 1, use Accelerator Pedal Low Idle Switch 1, SPN 558.
        static
        const
        J1939_SPN           spn91 = {
            91,
            0,
            NULL    /*&percent01*/,
            "Accelerator Pedal Position 1"
        };
        
        
        // SPN 92 - Percent Load At Current Speed - The ratio of actual engine percent
        // torque (indicated) to maximum indicated torque available at the current en-
        // gine speed, clipped to zero torque during engine braking.
        static
        const
        J1939_SPN           spn92 = {
            92,
            0,
            NULL    /*&percent03*/,
            "Percent Load At Current Speed"
        };
        
        
        // SPN 98 - Engine Oil Level - Ratio of current volume of engine sump oil
        // to maximum required volume.
        static
        const
        J1939_SPN           spn98 = {
            98,
            0,
            NULL    /*&percent01*/,
            "Engine Oil Level"
        };
        
        
        // SPN 99 - Engine Oil Filter Differential Pressure - Change in engine oil
        // pressure, measured across the filter, due to the filter and any accumulation
        // of solid or semisolid material on or in the filter.
        static
        const
        J1939_SPN           spn99 = {
            99,
            0,
            NULL    /*&pressure01*/,
            "Engine Oil Filter Differential Pressure"
        };
        
        
        // SPN 102 - Boost Pressure - Gage pressure of air measured downstream on the
        // compressor discharge side of the turbocharger. See also SPNs 1127-1130 for
        // alternate range and resolution. If there is one boost pressure to report
        // and this range and resolution is adequate, this parameter should be used.
        static
        const
        J1939_SPN           spn102 = {
            102,
            0,
            NULL    /*&pressure02*/,
            "Boost Pressure"
        };
        
        
        // SPN 110 - Engine Coolant Temperature - Temperature of liquid found in engine
        // cooling system.
        static
        const
        J1939_SPN           spn110 = {
            110,
            0,
            NULL    /*&temp01*/,
            "Engine Coolant Temperature"
        };
        
        
        // SPN 174 - Fuel Temperature - Temperature of fuel entering injectors.
        static
        const
        J1939_SPN           spn174 = {
            174,
            0,
            NULL    /*&temp01*/,
            "Fuel Temperature"
        };
        
        
        // SPN 175 - Engine Oil Temperature 1 - Temperature of the engine lubricant.
        static
        const
        J1939_SPN           spn175 = {
            175,
            0,
            NULL    /*&temp02*/,
            "Engine Oil Temperature 1"
        };
        
        
        // SPN 176 - Turbo Oil Temperature - Temperature of the turbocharger lubricant.
        static
        const
        J1939_SPN           spn176 = {
            176,
            0,
            NULL    /*&temp02*/,
            "Turbo Oil Temperature"
        };
        
        
        // SPN 190 - Engine Speed - Actual engine speed which is calculated over a
        // minimum crankshaft angle of 720 degrees divided by the number of cylinders.
        static
        const
        J1939_SPN           spn190 = {
            190,
            0,
            NULL    /*&velocityRotational01*/,
            "Engine Speed"
        };
        
        
        // SPN 512 - Driver's Demand Engine - Percent Torque - The requested torque
        // output of the engine by the driver. It is based on input from the following
        // requestors external to the powertrain: operator (via the accelerator pedal),
        // cruise control and/or road speed limit governor. Dynamic commands from inter-
        // nal powertrain functions such as smoke control, low- and high-speed engine
        // governing; ASR and shift control are excluded from this calculation. The
        // data is transmitted in indicated torque as a percent of the reference engine
        // torque. See PGN 65251 for the engine configuration message. Several status
        // bits are defined separately to indicate the request which is currently being
        // honored. This parameter may be used for shift scheduling.
        static
        const
        J1939_SPN           spn512 = {
            512,
            0,
            NULL    /*&percent02*/,
            "Driver's Demand Engine - Percent Torque"
        };
        
        
        // SPN 513 - Actual Engine - Percent Torque - The calculated output
        // torque of the engine. The data is transmitted in indicated torque as a
        // percent of reference engine torque (see the engine configuration message,
        // PGN 65251). The engine percent torque value will not be less than zero and
        // it includes the torque developed in the cylinders required to overcome
        // friction.
        static
        const
        J1939_SPN           spn513 = {
            513,
            0,
            NULL    /*&percent02*/,
            "Actual Engine - Percent Torque"
        };
        
        
        // SPN 558 - Accelerator Pedal 1 Low Idle Switch - Switch signal
        // which indicates the state of the accelerator pedal 1 low idle switch.
        // The low idle switch is defined in SAE J1843.
        // 00 Accelerator pedal 1 not in low idle condition
        // 01 Accelerator pedal 1 in low idle condition
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn558 = {
            558,
            0,
            NULL    /*&bits02*/,
            "Accelerator Pedal 1 Low Idle Switch"
        };
        
        
        // SPN 559 - Accelerator Pedal Kickdown Switch - Switch signal which
        // indicates whether the accelerator pedal kickdown switch is opened
        // or closed. The kickdown switch is defined in SAE J1843.
        // 00 Kickdown passive
        // 01 Kickdown active
        static
        const
        J1939_SPN           spn559 = {
            559,
            0,
            NULL    /*&bits01*/,
            "Accelerator Pedal Kickdown Switch"
        };
        
        
        // SPN 590 - Engine Idle Shutdown Timer State
        // 00 Inactive
        // 01 Active
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn590 = {
            590,
            0,
            NULL    /*&????*/,
            "Engine Idle Shutdown Timer State"
        };
        
        
        // SPN 591 - Engine Idle Shutdown Timer Function
        // 00  Disabled in calibration
        // 01  Enabled in calibration
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn591 = {
            591,
            0,
            NULL    /*&????*/,
            "Engine Idle Shutdown Timer Function"
        };
        
        
        // SPN 592 - Engine Idle Shutdown Timer Override
        // 00 Inactive
        // 01 Active
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn592 = {
            592,
            0,
            NULL    /*&????*/,
            "Engine Idle Shutdown Timer Override"
        };
        
        
        // SPN 593 - Engine Idle Shutdown has Shutdown Engine
        // 00 No
        // 01 Yes
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn593 = {
            593,
            0,
            NULL    /*&????*/,
            "Engine Idle Shutdown has Shutdown Engine"
        };
        
        
        // SPN 594 - Engine Idle Shutdown Driver Alert Mode
        // Status signal which indicates the status of the driver alert mode
        // of the idle shutdown timer system. While the driver alert mode is
        // active, the idle shutdown timer may be overridden.
        // 00 Inactive
        // 01 Active
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn594 = {
            594,
            0,
            NULL    /*&????*/,
            "Engine Idle Shutdown Driver Alert Mode"
        };
        
        
        // SPN 595 - Engine Idle Shutdown has Shutdown Engine
        // 00 Cruise control switched off
        // 01 Cruise control switched on
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn595 = {
            595,
            0,
            NULL    /*&????*/,
            "Cruise Control Active"
        };
        
        
        // SPN 605 - Refrigerant High Pressure Switch
        // 00 Pressure normal
        // 01 Pressure too high, compressor clutch may be disengaged
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn605 = {
            605,
            0,
            NULL    /*&????*/,
            "Refrigerant High Pressure Switch"
        };
        
        
        // SPN 875 - Refrigerant Low Pressure Switch
        // 00 Pressure normal
        // 01 Pressure too low, compressor clutch may be disengaged
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn875 = {
            875,
            0,
            NULL    /*&????*/,
            "Refrigerant Low Pressure Switch"
        };
        
        
        // SPN 899 - Engine Torque Mode - State signal which indicates which
        // engine torque mode is currently generating, limiting, or controlling
        // the torque. Note that the modes are not in prioritized order. Not all
        // modes may be relevant for a given device. Some devices may not implement
        // all functions. For typical priorities refer to Figures SPN512_A and
        // SPN512_B for engine control and Tables SPN518_A to SPN518_B for retarder
        // control. The data type of this parameter is measured.
        // Mode 0000b means 'No request': engine torque may range from 0 to full load
        //             only due to low idle governor output; retarder torque == 0
        //              (no braking).
        // Modes 0001b to 1110b indicate that there is either a torque request or
        //              the identified function is currently controlling the engine/
        //              retarder: engine/retarder torque may range from 0 (no fueling/
        //              no braking) to the upper limit.
        static
        const
        J1939_SPN           spn899 = {
            899,
            0,
            NULL    /*&bits03*/,
            "Engine Torque Mode"
        };
        
        
        // SPN 974 - Remote Accelerator Pedal Position - The ratio of actual position
        // of the remote analog engine speed/torque request input device (such as an
        // accelerator pedal or throttle lever) to the maximum position of the input
        // device. For example, in on-highway vehicles this could be an accelerator
        // control device that is external to the drivers cab or an accelerator that
        // is controlled by a hand lever from the operators seat. The Remote Accelerator
        // Enable Switch is SPN 969. This parameter enables the remote accelerator
        // operation. NOTE: See SPNs 28, 29, and 91 for additional accelerator position
        // parameters. If only one accelerator position exists on a vehicle, SPN 91
        // shall be used.
        static
        const
        J1939_SPN           spn974 = {
            974,
            0,
            NULL    /*&percent01*/,
            "Remote Accelerator Pedal Position"
        };
        
        
        // SPN 985 - A/C High Pressure Fan Switch
        // 00 Pressure normal
        // 01 Pressure too high, fan may be engaged
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn985 = {
            985,
            0,
            NULL    /*&????*/,
            "A/C High Pressure Fan Switch"
        };
        
        
        // SPN 1081 - Engine Wait to Start Lamp
        // Lamp signal which indicates that the engine is too cold to start
        // and the operator should wait until the signal becomes inactive
        // (turns off).
        // 00 Off
        // 01 On
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1081 = {
            1081,
            0,
            NULL    /*&????*/,
            "Engine Wait to Start Lamp"
        };
        
        
        // SPN 1107 - Engine Protection System Timer State
        // 00 Inactive
        // 01 Active
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1107 = {
            1107,
            0,
            NULL    /*&????*/,
            "Engine Protection System Timer State"
        };
        
        
        // SPN 1108 - Engine Protection System Timer Override
        // 00 Inactive
        // 01 Active
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1108 = {
            1107,
            0,
            NULL    /*&????*/,
            "Engine Protection System Timer Override"
        };
        
        
        // SPN 1109 - Engine Protection System Approaching Shutdown
        // 00 Not Approaching
        // 01 Approaching
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1109 = {
            1109,
            0,
            NULL    /*&????*/,
            "Engine Protection System Approaching Shutdown"
        };
        
        
        // SPN 1110 - Engine Protection System has Shutdown Engine
        // 00 No
        // 01 Yes
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1110 = {
            1110,
            0,
            NULL    /*&????*/,
            "Engine Protection System Timer State"
        };
        
        
        // SPN 1111 - Engine Protection System Configuration
        // 00 Disabled in calibration
        // 01 Enabled in calibration
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn1111 = {
            1111,
            0,
            NULL    /*&????*/,
            "Engine Protection System Configuration"
        };
        
        
        // SPN 1134 - Engine Intercooler Thermostat Opening - The current position
        // of the thermostat used to regulate the temperature of the engine intercooler.
        // A value of 0% represents the thermostat being completely closed and 100%
        // represents the thermostat being completely open.
        static
        const
        J1939_SPN           spn1134 = {
            1134,
            0,
            NULL    /*&percent01*/,
            "Engine Intercooler Thermostat Opening"
        };
        
        
        // SPN 1437 - Road Speed Limit Status - Status (active or not active) of the
        // system used to limit maximum vehicle velocity.
        // 00 - Active
        // 01 - Not Active
        // NOTE - While somewhat inconsistent with other J1939 status parameters, the
        // states defining 00 = active and 01 = inactive for Road Speed Limit Status
        // are NOT typographical errors, and should be implemented as stated.
        static
        const
        J1939_SPN           spn1437 = {
            1437,
            0,
            NULL    /*&bits01*/,
            "Road Speed Limit Status"
        };
        
        
        // SPN 1483 - Source Address of Controlling Device for Engine Control - The
        // source address of the SAE J1939 device currently controlling the engine.
        // It is used to expand the torque mode parameter (see SPN 899) in cases where
        // control is in response to an ECU that is not listed in Table SPN899_A. Its
        // value may be the source address of the ECU transmitting the message (which
        // means that no external SAE J1939 message is providing the active command)
        // or the source address of the SAE J1939 ECU that is currently providing the
        // active command in a TSC1 (see PGN 0) or similar message. Note that if this
        // parameter value is the same as the source address of the device transmitting
        // it, the control may be due to a message on a non-J1939 data link such as SAE
        // J1922 or a proprietary link.
        static
        const
        J1939_SPN           spn1483 = {
            1483,
            0,
            NULL    /*&sourceAddress*/,
            "Source Address of Controlling Device for Engine Control"
        };
        
        
        // SPN 1636 - Intake Manifold 1 Air Temperature (High Resolution) - Temperature
        // of pre-combustion air found in intake manifold of engine air supply system.
        // The higher resolution is required for control purposes.
        static
        const
        J1939_SPN           spn1636 = {
            1636,
            0,
            NULL    /*&temp02*/,
            "Intake Manifold 1 Air Temperature (High Resolution)"
        };
        
        
        // SPN 1637 - Engine Coolant Temperature (High Resolution) - Temperature of
        // liquid found in engine cooling system. The higher resolution is required
        // for control purposes.
        static
        const
        J1939_SPN           spn1637 = {
            1637,
            0,
            NULL    /*&temp02*/,
            "Engine Coolant Temperature (High Resolution)"
        };
        
        
        // SPN 1675 - Engine Starter Mode - There are several phases in a
        // starting action and different reasons why a start cannot take place.
        // 0000 start not requested
        // 0001 starter active, gear not engaged
        // 0010 starter active, gear engaged
        // 0011 start finished; starter not active after having been actively engaged
        //      (after 50ms mode goes to 0000) 0100 starter inhibited due to engine
        //       already running)
        // 0101 starter inhibited due to engine not ready for start (preheating)
        // 0110 starter inhibited due to driveline engaged or other transmission inhibit
        // 0111 starter inhibited due to active immobilizer
        // 1000 starter inhibited due to starter over-temp
        // 1001-1011 Reserved
        // 1100 starter inhibited - reason unknown
        // 1101 error (legacy implementations only; use 1110)
        // 1110 error
        // 1111 not available
        static
        const
        J1939_SPN           spn1675 = {
            1675,
            0,
            NULL    /*&bits03*/,
            "Engine Starter Mode"
        };
        
        
        // SPN 2432 - Engine Demand - Percent Torque - The requested torque output of
        // the engine by all dynamic internal inputs, including smoke control, noise
        // control and low and high speed governing.
        static
        const
        J1939_SPN           spn2432 = {
            2432,
            0,
            NULL    /*&percent02*/,
            "Engine Demand - Percent Torque"
        };
        
        
        // SPN 2812 - Engine Overspeed Test
        // 00 Engine Overspeed Test Not Active
        // 01 Engine Overspeed Test Active
        // 10 Reserved
        // 11 Not available
        static
        const
        J1939_SPN           spn2812 = {
            2812,
            0,
            NULL    /*&????*/,
            "Engine Overspeed Test"
        };
        
        
        // SPN 2813 - Engine Air Shutoff Command Status
        // 00 No
        // 01 Yes
        // 10 Error
        // 11 Not available
        static
        const
        J1939_SPN           spn2813 = {
            2813,
            0,
            NULL    /*&????*/,
            "Engine Air Shutoff Command Status"
        };
        
        
        // SPN 2814 - Engine Overspeed Test
        // 00 Disabled
        // 01 Enabled
        // 10 Reserved
        // 11 Not available
        static
        const
        J1939_SPN           spn2814 = {
            2814,
            0,
            NULL    /*&????*/,
            "Engine Overspeed Test"
        };
        
        
        // SPN 2815 - Engine Alarm Output Command Status
        // 00 Engine Alarm Output Command Not Active
        // 01 Engine Alarm Output Command Active
        // 10 Reserved
        // 11 Not available
        static
        const
        J1939_SPN           spn2815 = {
            2815,
            0,
            NULL    /*&????*/,
            "Engine Alarm Output Command Status"
        };
        
        
        // SPN 2848 - Engine Demand - Percent Torque - The requested torque output of
        static
        const
        J1939_SPN           spn2848 = {
            2848,
            0,
            NULL    /*&bits64*/,
            ""
        };
        
        
        static
        const
        J1939_PGNSPN        pgn37632spns[1] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 37632, 2848,   0,    0,      0,    0, &spn2848 }
        };
        
        static
        const
        J1939_PGNSPN        pgn60928spns[1] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 60928, 2848,   0,    0,     0,     0, &spn2848 }
        };
        
        static
        const
        J1939_PGNSPN        pgn61443spns[6] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 61443,  558,   0,    0,     0,     0, &spn558 },
            { 61443,  559,   0,    0,     0,     0, &spn559 },
            { 61443, 1437,   0,    0,     0,     0, &spn1437 },
            { 61443,   91,   1,    0,     0,     0, &spn91 },
            { 61443,   92,   2,    0,     0,     0, &spn92 },
            { 61443,  974,   3,    0,     0,     0, &spn974 }
        };
        
        static
        const
        J1939_PGNSPN        pgn61444spns[7] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 61444,  899,   0,    0,     0,    0,  &spn899 },
            { 61444,  512,   1,    0,     0,    0,  &spn512 },
            { 61444,  513,   2,    0,     0,    0,  &spn513 },
            { 61444,  190,   3,    0,     0,    0,  &spn190 },
            { 61444, 1483,   5,    0,     0,    0,  &spn1483 },
            { 61444, 1675,   6,    0,     0,    0,  &spn1675 },
            { 61444, 2432,   7,    0,     0,    0,  &spn2432 }
        };
        
        static
        const
        J1939_PGNSPN        pgn65129spns[2] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65129, 1636,   0,    0,     0,    0,  &spn1636 },
            { 65129, 1637,   2,    0,     0,    0,  &spn1637 }
        };
        
        static
        const
        J1939_PGNSPN        pgn65252spns[18] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65252,  593,   2,    0,     0,    0,  &spn593 },
            { 65252,  594,   2,    2,     0,    0,  &spn594 },
            { 65252,  592,   2,    4,     0,    0,  &spn592 },
            { 65252,  590,   2,    6,     0,    0,  &spn590 },
            { 65252,  591,   2,    6,     1,    0,  &spn591 },
            { 65252,  985,   2,    0,     2,    0,  &spn985 },
            { 65252,  875,   2,    2,     2,    0,  &spn875 },
            { 65252,  605,   2,    4,     2,    0,  &spn605 },
            { 65252, 1081,   2,    0,     3,    0,  &spn1081 },
            { 65252, 1110,   2,    0,     4,    0,  &spn1110 },
            { 65252, 1109,   2,    2,     4,    0,  &spn1109 },
            { 65252, 1108,   2,    4,     4,    0,  &spn1108 },
            { 65252, 1107,   2,    6,     4,    0,  &spn1107 },
            { 65252, 1111,   2,    6,     5,    0,  &spn1111 },
            { 65252, 2815,   2,    0,     6,    0,  &spn2815 },
            { 65252, 2814,   2,    2,     6,    0,  &spn2814 },
            { 65252, 2813,   2,    4,     6,    0,  &spn2813 },
            { 65252, 2812,   2,    6,     6,    0,  &spn2812 }
        };
        
        
        static
        const
        J1939_PGNSPN        pgn65262spns[6] = {
            //                    Bit    Byte
            // PGN    SPN  cBits Offset Offset rsvd spnDef
            { 65262,  110,   0,    0,     0,    0,  &spn110 },
            { 65262,  174,   1,    0,     0,    0,  &spn174 },
            { 65262,  175,   2,    0,     0,    0,  &spn175 },
            { 65262,  176,   3,    0,     0,    0,  &spn176 },
            { 65262,   52,   6,    0,     0,    0,  &spn52 },
            { 65262, 1134,   7,    0,     0,    0,  &spn1134 }
        };
        

#ifdef XYZZY
        //FIXME:
        static
        const
        J1939_PGN_ENTRY     pgn37632 = {
        //   PGN    msFreq dlc priority cSpns rsvd pSpns
            37632,    0,    8,    6,     1,     0, pgn37632spns,
            "???"
        };
#endif
        
        
        
        
        
        const
        J1939_PGN_ENTRY     pgn0_entry = {
            // PGN 0  0x000000 - Torque/Speed Control 1 - TSC1
            0x00000000,
            50,                 // msFreq (to Retarder)(10ms to Engine)
            8,                  // dlc
            3,                  // priority
            7,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn256_entry = {
            // PGN 0  0x000100 - Transmission Control 1 - TC1
            0x00000100,
            50,                 // msFreq (only when active)
            8,                  // dlc
            3,                  // priority
            17,                 // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn59392_entry = {
            // PGN 59392  0x00E800 - ACK/NAK
            0x0000E800,
            0,                  // msFreq
            8,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn59904_entry = {
            // PGN 59904  0x00EA00 (PDU1) - Request for PGN
            0x0000EA00,
            0,                  // msFreq
            3,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn60416_entry = {
            // PGN 60416  0x00EC00 -
            0x0000EE00,
            0,                  // msFreq
            8,                  // dlc
            7,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn60928_entry = {
            // PGN 60928  0x00EE00 - Claim Address/Cannot Claim Address
            0x0000EE00,
            0,                  // msFreq
            8,                  // dlc
            6,                  // priority
            1,                  // cSPNs
            0,                  // --reserved--
            pgn60928spns,       // SPN Table Pointer
            "Claim Address/Cannot Claim Address"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61184_entry = {
            // PGN 61184  0x00EF00 - Proprietary A
            0x0000EF00,
            0,                  // msFreq
            8,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61440_entry = {
            // PGN 61440  0x00F000 - Electronic Retarder Controller 1 - ERC1
            0x0000F000,
            100,                // msFreq
            8,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61442_entry = {
            // PGN 61442  0x00F002 - Electronic Transmission Controller 1 - ETC1
            0x0000F002,
            10,                 // msFreq
            8,                  // dlc
            3,                  // priority
            9,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61443_entry = {
            // PGN 61443  0x00F003 - Electronic Engine Controller 2 - EEC2
            0x0000F003,
            50,                 // msFreq
            8,                  // dlc
            3,                  // priority
            6,                  // cSPNs
            0,                  // --reserved--
            pgn61443spns,       // SPN Table Pointer
            "Electronic Engine Controller 2 - EEC2"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61444_entry = {
            // PGN 61444  0x00F004 - Electronic Engine Controller 1 - EEC1
            0x0000F004,
            100,                // msFreq
            8,                  // dlc
            3,                  // priority
            7,                  // cSPNs
            0,                  // --reserved--
            pgn61444spns,       // SPN Table Pointer
            "Electronic Engine Controller 1 - EEC1"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn61445_entry = {
            // PGN 61445  0x00F005 - Electronic Transmission Controller 1 - ETC2
            0x0000F005,
            100,                // msFreq
            8,                  // dlc
            6,                  // priority
            5,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65098_entry = {
            // PGN 65098  0x00FE4A - Electronic Transmission Controller 7 - ETC7
            0x0000FE4A,
            100,                // msFreq
            8,                  // dlc
            6,                  // priority
            11,                 // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65129_entry = {
            // PGN 65129  0x00FE69 - Engine Temperature 3 - ET3
            0x0000FE69,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            2,                  // cSPNs
            0,                  // --reserved--
            pgn65129spns,       // SPN Table Pointer
            "Engine Temperature 3 - ET3"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65226_entry = {
            // PGN 65226  0x00FECA - Active Diagnostic Trouble Codes - DM1
            0x0000FECA,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65247_entry = {
            // PGN 65247  0x00FEDF - Electronic Engine Controller 3 - EEC3
            0x0000FEDF,
            250,                // msFreq
            8,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65249_entry = {
            // PGN 65249  0x00FEE1 - Retarder Configuration - RC -
            0x00FEE1,
            5000,               // msFreq
            19,                 // dlc
            6,                  // priority
            14,                 // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65251_entry = {
            // PGN 65251  0x00FEE3 - Engine Configuration 1 - EC1 -
            0x00FEE1,
            5000,               // msFreq
            39,                 // dlc
            6,                  // priority
            14,                 // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65252_entry = {
            // PGN 65251  0x00FEE4 - Shutdown           - SHUTDOW -
            0x00FEE4,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            18,                 // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65262_entry = {
            // PGN 65262  0x00FEEE - Engine Temperature 1 - ET1
            0x0000FEEE,
            1000,               // msFreq
            8,                  // dlc
            6,                  // priority
            6,                  // cSPNs
            0,                  // --reserved--
            pgn65262spns,       // SPN Table Pointer
            "Engine Temperature 1 - ET1"
        };
        
        
        const
        J1939_PGN_ENTRY     pgn65265_entry = {
            // PGN 65265  0x00FEF1 - Cruise Control/Vehicle Speed - CCVS
            0x0000FEF1,
            100,                // msFreq
            8,                  // dlc
            6,                  // priority
            0,                  // cSPNs
            0,                  // --reserved--
            NULL                // SPN Table Pointer
        };
        
        
        const
        J1939_PGN_ENTRY     *pgn_index[] = {
            &pgn0_entry,
            &pgn256_entry,
            &pgn59392_entry,
            &pgn59904_entry,
            &pgn60416_entry,
            &pgn60928_entry,
            &pgn61184_entry,
            &pgn61440_entry,
            &pgn61442_entry,
            &pgn61443_entry,
            &pgn61444_entry,
            &pgn61445_entry,
            &pgn65098_entry,
            &pgn65129_entry,
            &pgn65226_entry,
            &pgn65247_entry,
            &pgn65249_entry,
            &pgn65262_entry,
            &pgn65265_entry,
            NULL
        };
        
        
        const
        J1939_PGN_TABLE     pgn_table = {
            (sizeof(pgn_index)/sizeof(J1939_PGN_ENTRY *)) - 1,
            0,
            &pgn_index
        };
        
        
        
        


 
    /****************************************************************
    * * * * * * * * * * *  Internal Subroutines   * * * * * * * * * *
    ****************************************************************/



    /****************************************************************
    * * * * * * * * * * *  External Subroutines   * * * * * * * * * *
    ****************************************************************/


    //===============================================================
    //                      *** Class Methods ***
    //===============================================================

    J1939TBL_DATA * j1939tbl_Alloc(
    )
    {
        J1939TBL_DATA   *this;
        uint32_t        cbSize = sizeof(J1939TBL_DATA);
        
        // Do initialization.
        
        this = obj_Alloc( cbSize );
        
        // Return to caller.
        return this;
    }



    //---------------------------------------------------------------
    //                  SPN to Signed Value
    //---------------------------------------------------------------
    
    int32_t         j1939tbl_SpnToS32(
        J1939_SPN_TYPE  *pType,
        uint16_t        data
    )
    {
        int32_t         value = 0;
        
        if (pType) {
            // The order of operations is important since we are
            // working with integers.
            // We expand some of the more common multiplications
            // and divisions to save time.
            if (1 == pType->mult) {
                value = data;
            }
            else if (2 == pType->mult) {
                value = (data << 1);
            }
            else if (4 == pType->mult) {
                value = (data << 2);
            }
            else {
                value = (data * pType->mult);
            }
            value += pType->round;
            if (1 == pType->div)
                ;
            else if (2 == pType->div) {
                value >>= 1;
            }
            else if (4 == pType->div) {
                value >>= 2;
            }
            else {
                value /= pType->div;
            }
            value += pType->offset;
        }
        
        // Return to caller.
        return value;
    }
    
    
    
    

    //===============================================================
    //                      P r o p e r t i e s
    //===============================================================

    uint16_t        j1939tbl_getPriority(
        J1939TBL_DATA     *this
    )
    {

        // Validate the input parameters.
#ifdef NDEBUG
#else
        if( !j1939tbl_Validate( this ) ) {
            DEBUG_BREAK();
        }
#endif

        //return this->priority;
        return 0;
    }

    bool            j1939tbl_setPriority(
        J1939TBL_DATA     *this,
        uint16_t        value
    )
    {
#ifdef NDEBUG
#else
        if( !j1939tbl_Validate( this ) ) {
            DEBUG_BREAK();
        }
#endif
        //this->priority = value;
        return true;
    }



    uint32_t        j1939tbl_getSize(
        J1939TBL_DATA       *this
    )
    {
#ifdef NDEBUG
#else
        if( !j1939tbl_Validate( this ) ) {
            DEBUG_BREAK();
        }
#endif
        return 0;
    }



    

    //===============================================================
    //                          M e t h o d s
    //===============================================================


    //---------------------------------------------------------------
    //                        D e a l l o c
    //---------------------------------------------------------------

    void            j1939tbl_Dealloc(
        OBJ_ID          objId
    )
    {
        J1939TBL_DATA   *this = objId;

        // Do initialization.
        if (NULL == this) {
            return;
        }        
#ifdef NDEBUG
#else
        if( !j1939tbl_Validate(this) ) {
            DEBUG_BREAK();
            return;
        }
#endif

        obj_Dealloc(this);
        this = NULL;

        // Return to caller.
    }



    //---------------------------------------------------------------
    //                          I n i t
    //---------------------------------------------------------------

    J1939TBL_DATA *   j1939tbl_Init(
        J1939TBL_DATA       *this
    )
    {
        uint32_t        cbSize = sizeof(J1939TBL_DATA);
        
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        
        this = obj_Init( this, cbSize, OBJ_IDENT_J1939TBL );
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        obj_setVtbl(this, (OBJ_IUNKNOWN *)&j1939tbl_Vtbl);
        
        //this->stackSize = obj_getMisc1(this);

    #ifdef NDEBUG
    #else
        if( !j1939tbl_Validate(this) ) {
            DEBUG_BREAK();
            return OBJ_NIL;
        }
        //BREAK_NOT_BOUNDARY4(&cbp->thread);
    #endif

        return this;
    }

     

    //---------------------------------------------------------------
    //                      V a l i d a t e
    //---------------------------------------------------------------

    #ifdef NDEBUG
    #else
    bool            j1939tbl_Validate(
        J1939TBL_DATA      *this
    )
    {
        if(this) {
            if ( obj_IsKindOf(this, OBJ_IDENT_J1939TBL) )
                ;
            else
                return false;
        }
        else
            return false;
        if( !(obj_getSize(this) >= sizeof(J1939TBL_DATA)) )
            return false;

        // Return to caller.
        return true;
    }
    #endif


    
    
    
#ifdef	__cplusplus
}
#endif


